--
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/8/10 20:31
---

local errorCode = {}
local function add(err)
    errorCode[err.code] = err
    return err.code
end

errorCode.SystemError = {
    success            = add{code = 0, message = "请求成功"},
    unknow             = add{code = 1, message = "未知错误"},
    argument           = add{code = 2, message = "参数错误" },
    protoNotExists     = add{code = 3, message = "不存在此协议"},
    serviceIsStoped    = add{code = 4, message = "服务故障" },
    sessionNotExists   = add{code = 5, message = "不存在此Session"},
    moduleNotImpl      = add{code = 6, message = "此模块未实现"},
    protoNotImpl       = add{code = 7, message = "此协议未实现"},
    noLogin            = add{code = 8, message = "尚未登录" },
    packHeaderNil      = add{code = 9, message = "包头是空的"},
    forward            = add{code = 10, message = "重定向"},
    serverMaintenance  = add{code = 11, message = "服务器维护"},
    busy               = add{code = 12, message = "服务忙"},
    logined            = add{code = 13, message = "已登录"},
    dbServerStoped     = add{code = 14, message = "数据服务故障"},
    noLoginGame        = add{code = 15, message = "未进入游戏"},
    notOnline          = add{code = 16, message = "玩家不在线"},
    saveCacheFailed    = add{code = 17, message = "写入缓存失败"},
    logoutingGame      = add{code = 18, message = "正在退出游戏中"},
    noUseableService   = add{code = 19, message = "没有可用的服务"},
    sessionInvalid     = add{code = 20, message = "此session是非法的"},
    sessionTimeout     = add{code = 21, message = "此session已过期"},
    sessionNoMatch     = add{code = 22, message = "会话不匹配"},
    serviceNotImpl     = add{code = 23, message = "此服务未实现"},
    functionNotOpen    = add{code = 24, message = "此功能尚未开放"},
    serviceIsOpened    = add{code = 25, message = "服务已开放"},
    serviceIsClosed    = add{code = 26, message = "服务已关闭"},
    serviceIsOffline   = add{code = 27, message = "服务已下线"},
    msgTimeOut         = add{code = -1, message = "消息超时"},
}

errorCode.authError =   {
    loginAccountFill    = add({code=1001,message="账号或者密码错误"}),
    accountExist        = add({code=1002,message="账号已经存在"}),
    accountAndPwdIsNull = add({code=1003,message="账号或者密码不能为空"}),
    roleIdNoExist       = add({code=1004,message="无效的用户id或者token无效"}),
}

return errorCode