---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/8/10 19:43
---

local this =
{
    GATE = "gate", --网关服务器
    DB   = "gate", --数据服
}
return this