---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/9/14 0014 21:03
---
local ctrl = require("ctrl")

local this = {}

function this.login(gamesession)
    return ctrl.login(gamesession)
end

function this.chat(gamesession,data)
    return ctrl.chat(gamesession,data)
end

function this.quit(gamesession)
    return ctrl.quit(gamesession)
end



return this