---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/9/14 0014 20:46
---
local skynet = require("skynet")
local service     = require "service_base"
local serviceNames     = require "serviceNames"

local ctrl = require("ctrl")
service.modules.chatserver = require("impl")
local command = service.command

function command.userOffline(gs)
    ctrl.userOffline(gs)
    --instanceDesk:userOffline(gs)
end

function service.onStart()
    ctrl.init()
    print("chat server start")
    skynet.register(serviceNames.uniqueService.chatserver)
end

service.start()