---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/8/23 18:32
---

local class = require("class")
local dataBase = require("data.dataBase")
---@class accountData : DataBase
---@field account string
---@field pwd string
---@field userid string
local this = class(dataBase)
this.personalId = "accountdata"
this.needSavetoDB = false
this.keyName = "account"

this.columnNameOptions =
{
    account="varchar(255) NOT NULL",
    pwd="varchar(255)",
    userid ="int",
}

function this:_init(account,pwd,userid)
    self.account = account
    self.pwd = pwd
    self.userid = userid
end

return this