---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/8/22 17:14
---
local logger = require("logger")
local dataBase = require("data.dataBase")
local class = require("class")
local cjson = require("cjson")
---@class userData : DataBase
local this = class(dataBase)
this.keyName = "roleId"
this.personalId = "userdata"
this.needSavetoDB = true
this.columnNameOptions =
{
    roleId="int NOT NULL",
    nickName="varchar(255)",
    headUrl="varchar(500)",
    sex="int",
    signature="varchar(255)",
    constellation="int",
    city="varchar(255)",
    county="varchar(255)",
    weChat="varchar(255)",
    gold="int",
    diamond="int",
    unionid="varchar(255)",
    createTime="timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP",
    lastLoginTime="timestamp NULL DEFAULT CURRENT_TIMESTAMP",
}
function this:_init(userid)
    self.roleId = userid
    self.nickName = ""
    self.headUrl = ""
    self.sex = 1
    self.signature = "这个家伙很懒，什么也没留下"
    self.constellation = 0
    self.county = ""
    self.city = ""
    self.weChat = ""
    self.gold = 0
    self.diamond = 0
    self.unionId = ""
     self.createTime = os.date("%Y-%m-%d %H:%M:%S")
    self.lastLoginTime = os.date("%Y-%m-%d %H:%M:%S")
    end

function this:ToRespUserData()
    return {
        roleId = self.roleId,
        nickName = self.nickName,
        headUrl = self.headUrl,
        sex = self.sex,
        signature = self.signature,
        constellation = self.constellation,
        county = self.county,
        city = self.city,
        weChat =self.weChat,
        gold=self.gold,
        diamond=self.diamond
    }
end
return this
