---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/8/23 14:07
---
local class = require("class")
local dataBase = require("data.dataBase")
---@class WXData : DataBase
---@field openid string
---@field nickname string
---@field unionid string
---@field sex int
---@field headUrl string
---@field city string
---@field country string
---@field userid string
---@field token string
local this = class(dataBase)
this.keyName = "openid"
this.personalId = "wxdata"
this.needSavetoDB = true
this.columnNameOptions=
{
    openid="varchar(255)",
    nickname="varchar(255)",
    unionid="varchar(255) NOT NULL",
    sex="int",
    headUrl="varchar(500)",
    city="varchar(255)",
    country="varchar(255)",
    userid="int",
    token="varchar(255)",
    sessionkey="varchar(255)"
}

function this:_init(openid,unionid,userid,sessionkey)
    self.openid = openid
    self.unionid = unionid
    self.userid = userid
    self.sessionkey = sessionkey
end

return this