---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/8/20 0:30
---
local skynet = require("skynet")
local cjson = require("cjson")
local this = {}
---@param gs Gamesession
---@param data any
function this.test(gs,data)
    --skynet.error("收到服务器消息：100"..cjson.encode(data))
    local ec = 0
    return ec,data
end
return this