---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/9/13 0013 12:06
---
local json = {}

local cjson
local function safeLoad()
    cjson = require("cjson")
end

if not pcall(safeLoad) then
    cjson = nil
end

function json.encode(var)
    local status, result = pcall(cjson.encode, var)
    if status then return result end
    print(string.format("json.encode() - encoding failed: %s", tostring(result)))
end

function json.decode(text)
    local status, result = pcall(cjson.decode, text)
    if status then return result end
    print(string.format("json.decode() - decoding failed: %s", tostring(result)))
    return nil
end

function json.encode_sparse_array(...)
    cjson.encode_sparse_array(...)
end

if cjson then
    json.null = cjson.null
else
    json = nil
end

return json